version: 2

sources:
  - name: raw_source                
    database: raw_db                 
    schema: raw_schema               
    tables:
      - name: customers
        description: "Raw customer data from the source system."
      - name: products
        description: "Raw product data before transformation."
      - name: transactions
        description: "Raw transaction data from sales."
      - name: country_region
        description: "Raw region data from sales."
